export enum PaymentActionTypes {
  FETCH_CATEGORIES = '@@home/FETCH_CATEGORIES',
  FETCH_CATEGORIES_SUCCESS = '@@home/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE = '@@home/FETCH_CATEGORIES_FAILURE',
}
